name: PR Auto Label
description: Automatically label PRs
author: tobytheghost

runs:
  using: "composite"
  steps:
    - name: Setup bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest

    - name: Pull files
      uses: actions/checkout@v3
    
    - name: Install dependencies
      shell: bash
      run: |
        ls
        bun install
        bun run index.ts
    